    # =========================
    # DATABASE LOCALE
    # =========================
    spring.datasource.url=jdbc:postgresql://localhost:5432/content_manager
    spring.datasource.username=postgres
    spring.datasource.password=pass
    spring.datasource.driver-class-name=org.postgresql.Driver

    # =========================
    # JPA / HIBERNATE
    # =========================
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

    spring.jpa.properties.hibernate.format_sql=true

    # =========================
    # LOGGING
    # =========================
    logging.level.org.springframework.security=DEBUG
    logging.level.org.springframework.orm.jpa=DEBUG
    logging.level.org.springframework.web=DEBUG

    # =========================
    # DEVTOOLS
    # =========================
    spring.devtools.restart.enabled=true

    # =========================
    # JWT (se lo usi in locale)
    # =========================
    jwt.secret=xxxxx

    # =========================
    # MAIL (opzionale in dev)
    # =========================
    spring.mail.host=smtp.libero.it
    spring.mail.port=587
    spring.mail.username=tuo_mail
    spring.mail.password=PASSWORD_O_ENV

    spring.mail.properties.mail.smtp.auth=true
    spring.mail.properties.mail.smtp.starttls.enable=true