spring.application.name=MemoriaWebApp-senzaSicurezza

# JWT
jwt.secret=bXlTdXBlclNlY3JldEtleTEyMw==

# LOGGING
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework=DEBUG

# DEVTOOLS
spring.devtools.restart.enabled=true

# =========================
# DATABASE POSTGRESQL
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/content_manager
spring.datasource.username=postgres
spring.datasource.password=pass
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.type=trace

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

# =========================
# THYMELEAF
# =========================
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# =========================
# MAIL (LIBERO)
# =========================
spring.mail.host=smtp.libero.it
spring.mail.port=587
spring.mail.username=saisei1099@libero.it
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.enable=false
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

