spring.datasource.url=jdbc:postgresql://dpg-d8ko388g4nts73800qlg-a.oregon-postgres.render.com:5432/db_content_manager
spring.datasource.username=user_db
spring.datasource.password=yu4AW7p4JoklRUCBbFERul1mG8eOrVvq

server.port=${PORT}