spring.application.name=MemoriaWebApp-senzaSicurezza



# Abilitare il restart automatico:
spring.devtools.restart.enabled=true

# Configurazione database
spring.datasource.url=jdbc:mysql://localhost:3306/content_manager
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurazione JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configurazione thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html



# Logga le query con formattazione
spring.jpa.properties.hibernate.format_sql=true

# Abilita il logging dei parametri delle query (per vedere anche i valori passati nelle query)
spring.jpa.properties.hibernate.type = trace

# Imposta il livello di log a "DEBUG" per Hibernate
logging.level.org.hibernate.SQL=DEBUG

# Imposta il livello di log per Hibernate per i dettagli di binding (parametri delle query)
logging.level.org.hibernate.type.descriptor.sql=TRACE